---
items:
- name: BLACK_STONE_WEAPON
  id: 16001
- name: BLACK_STONE_ARMOR
  id: 16002
- name: HARD_BLACK_CRYSTAL_SHARD
  id: 4997
- name: SHARP_BLACK_CRYSTAL_SHARD
  id: 4998
- name: CONCENTRATED_MAGICAL_BLACK_STONE_WEAPON
  id: 16004
- name: CONCENTRATED_MAGICAL_BLACK_STONE_ARMOR
  id: 16005
- name: MEMORY_FRAGMENT
  id: 44195
- name: CAPHRAS_STONE
  id: 721003
- name: ANCIENT_RELIC_CRYSTAL_SHARD
  id: 40218
- name: FORBIDDEN_BOOK
  id: 40220
- name: SCROLL_WRITTEN_IN_ANCIENT_LANGUAGE
  id: 40228
